name: jaguar_retrofit
description: Retrofit inspired declarative HTTP client for Dart.
version: 2.8.8
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/Jaguar-dart/client

environment:
  sdk: ">=2.0.0-dev.65 <3.0.0"

dependencies:
  jaguar_serializer: ^2.2.4
  http: ^0.12.0
  meta: ^1.1.5
  jaguar_mimetype: ^1.0.0
  jaguar_resty:
    git:
      url: git://github.com/surfstudio/flutter-client.git
      path: resty
      ref: dio-2

dev_dependencies:
  pedantic:
  test: ^1.3.0
  jaguar_serializer_cli:
    git:
      url: git://github.com/surfstudio/flutter-jaguar-serializer.git
      path: serializer_cli
      ref: fixes
  build_runner:
  jaguar: ^2.4.1
  jaguar_retrofit_gen:
    path: ../retrofit_gen

#dependency_overrides:
#  jaguar_resty:
#    path: ../resty
